### ISSUE TITLE
TypeError: __init__() got multiple values for argument 'options'

### ISSUE THREAD

**Issue by AndDevDE** [Kalebu/alright#126]
Hey there, I tried installing Alright on my Pi following the instructions provided by @BilalBhatti in [Issue 31](https://github.com/Kalebu/alright/issues/31), but every time I try running the code it gives this error:

`
Traceback (most recent call last):
  File "/home/pi/alright/watest.py", line 5, in <module>
    messenger = WhatsApp()
  File "/home/pi/alright/alright/__init__.py", line 38, in __init__
    browser = webdriver.Chrome(
TypeError: __init__() got multiple values for argument 'options'
`

How can I fix this?

**Comment by ZMensRain** [comment]
@AndDevDE 
I had a very similar problem the fix I found was to remove  `ChromeDriverManager().install()`, on line 39 in the __init__.py file and that fixed it. i was on a windows machine not pi but try it.

**Comment by kkg0** [comment]
![image](https://github.com/Kalebu/alright/assets/82566963/1fae8da7-857b-4712-bffa-dd3df031ed13)
