### ISSUE TITLE
TypeError: WebDriver.__init__() got multiple values for argument 'options'

### ISSUE THREAD

**Issue by dhmyess** [Kalebu/alright#142]
Hi I've got error when trying to execute messenger = WhatsApp()

Got errort message:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dharma/.local/lib/python3.10/site-packages/alright/__init__.py", line 39, in __init__
    browser = webdriver.Chrome(
TypeError: WebDriver.__init__() got multiple values for argument 'options'

>>> selenium.__version__
'4.13.0'
Chrome Version 117.0.5938.132

OS Linux Mint 21.2 Victoria

**Comment by vepman** [comment]
Yes, me too.

`Chrome Version 119.0.6045.106`

**Comment by mbk87234** [comment]
I am facing the same error. The error probably arose since a recent update of selenium. A solution has been suggested here but I am not sure how to apply that. Lets hope that the developer fixes it.
https://stackoverflow.com/questions/76428561/typeerror-webdriver-init-got-multiple-values-for-argument-options

Removing the line 40 "ChromeDriverManager().install()," from __ init __.py solved the issue for me

**Comment by dreamlinepl** [comment]
Have you been able to remove that bug?

**Comment by dhmyess** [comment]
Can not use selenium latest version, use selenium 4.2.0
just pip install selenium==4.2.0

but i've got new issue today, looks like whatsapp web change again

**Comment by charvakanand** [comment]
> I am facing the same error. The error probably arose since a recent update of selenium. A solution has been suggested here but I am not sure how to apply that. Lets hope that the developer fixes it. https://stackoverflow.com/questions/76428561/typeerror-webdriver-init-got-multiple-values-for-argument-options
> 
> Removing the line 40 "ChromeDriverManager().install()," from __ init __.py solved the issue for me

this is currently working for me as well!
