### ISSUE TITLE
Unexpected indent

### ISSUE THREAD

**Issue by rssws** [Kalebu/alright#52]
See the error log:

```text
python3 main.py
Traceback (most recent call last):
  File "(...)/main.py", line 1, in <module>
    from alright import WhatsApp
  File "(...)/python3.8/site-packages/alright/__init__.py", line 207
    for i in ctrl_element:
    ^
```

Apparently, there is a wrong indent in `__init__.py`.

**Comment by Kalebu** [comment]
Resolved it, Thank you for pointing out
