### ISSUE TITLE
Crashes during messanger creation

### ISSUE THREAD

**Issue by shusterboris** [Kalebu/alright#7]
Hi! I'm facing with issue!
Can't start. Thank you advance!

messenger = WhatsApp()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python39\lib\site-packages\alright-1.1-py3.9.egg\alright\__init__.py", line 27, in __init__
  File "C:\Program Files\Python39\lib\site-packages\selenium-4.0.0b4-py3.9.egg\selenium\webdriver\chrome\webdriver.py", line 69, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "C:\Program Files\Python39\lib\site-packages\selenium-4.0.0b4-py3.9.egg\selenium\webdriver\chromium\webdriver.py", line 93, in __init__
    RemoteWebDriver.__init__(
  File "C:\Program Files\Python39\lib\site-packages\selenium-4.0.0b4-py3.9.egg\selenium\webdriver\remote\webdriver.py", line 248, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Program Files\Python39\lib\site-packages\selenium-4.0.0b4-py3.9.egg\selenium\webdriver\remote\webdriver.py", line 339, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Program Files\Python39\lib\site-packages\selenium-4.0.0b4-py3.9.egg\selenium\webdriver\remote\webdriver.py", line 400, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python39\lib\site-packages\selenium-4.0.0b4-py3.9.egg\selenium\webdriver\remote\errorhandler.py", line 236, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot create default profile directory
Stacktrace:
Backtrace:
        Ordinal0 [0x002A3733+2504499]
        Ordinal0 [0x0023C401+2081793]
        Ordinal0 [0x00142628+1058344]
        Ordinal0 [0x0015F6B0+1177264]
        Ordinal0 [0x0015CFEA+1167338]
        Ordinal0 [0x00159DC3+1154499]
        Ordinal0 [0x00189B82+1350530]
        Ordinal0 [0x001897DA+1349594]
        Ordinal0 [0x00185D4B+1334603]
        Ordinal0 [0x001622B4+1188532]
        Ordinal0 [0x00163149+1192265]
        GetHandleVerifier [0x0041FB8C+1512252]
        GetHandleVerifier [0x004CB0DF+2214031]
        GetHandleVerifier [0x00324BC3+484211]
        GetHandleVerifier [0x00323E69+480793]
        Ordinal0 [0x0024218D+2105741]
        Ordinal0 [0x002466E8+2123496]
        Ordinal0 [0x00246827+2123815]
        Ordinal0 [0x0024FB73+2161523]
        BaseThreadInitThunk [0x76F4FA29+25]
        RtlGetAppContainerNamedObjectPath [0x77CF7A9E+286]
        RtlGetAppContainerNamedObjectPath [0x77CF7A6E+238]
        (No symbol) [0x00000000]

**Comment by Kalebu** [comment]
On the window, you could try commenting on line 27 on the *alright/.__init__.py* and adding 

```
options.add_argument('--profile-directory=Default')
options.add_argument('--user-data-dir=C:/Temp/ChromeProfile')
```
 and then installing manually, Let me know if it works 

Here a [Reference](https://stackoverflow.com/questions/36434415/chromedriver-cannot-create-default-profile-directory)

**Comment by shusterboris** [comment]
I'm still see strange message (see below), but It's working! Many thanks! Are you planing add method, something like readUserMessages()? From my point of view it would be very usefull. Thanks again. For some time I have been thinking  to write a simple auto answer bot for my needs. And the Facebook account registration and submission requirements are so bizarre.

DevTools listening on ws://127.0.0.1:57766/devtools/browser/2817ba5e-d8f8-4ac6-b728-37d18037776d
[24820:844:0624/114223.172:ERROR:device_event_log_impl.cc(214)] [11:42:23.173] USB: usb_device_handle_win.cc:1058 Failed to read descriptor from node connection: ╧Ёшёюхфшэхээюх ъ ёшёЄхьх єёЄЁющёЄтю эх ЁрсюЄрхЄ. (0x1F)
[24820:844:0624/114223.173:ERROR:device_event_log_impl.cc(214)] [11:42:23.174] USB: usb_device_handle_win.cc:1058 Failed to read descriptor from node connection: ╧Ёшёюхфшэхээюх ъ ёшёЄхьх єёЄЁющёЄтю эх ЁрсюЄрхЄ. (0x1F)

**Comment by Kalebu** [comment]
Hello, @shusterboris  I'm glad it worked, so I'm not using window not really be sure what might be causing that..

I will see the possibility to add *read_user_messages()* if doable then soon will be added

Stay tuned  !!
