### ISSUE TITLE
error sending message 

### ISSUE THREAD

**Issue by mohamedallam3** [Kalebu/alright#76]
hello sir,  
i install your app in my ubuntu machine , and it work , when i use class of find user it work and get the specific user, but when i send message i get exception error.
message of exception is:   
element not interactable

**Comment by euriconicacio** [comment]
Hi, @mohamedallam3 .

1. Could you please send more details onthe error? Part of the terminal log would be nice.


2. While that, could you try this approach, please?

`messenger = WhatsApp() messenger.find_by_username("John") messenger.just_type_and_send_message("Bla\nBla\nBla") messenger.browser.quit()`

Thanks a lot!

**Comment by limlaw** [comment]
same here, since chrome 103 or whatsapp update this everything is breaking.

I am trying the basic ones example

from alright import WhatsApp
messenger = WhatsApp()
messenger.find_user('2557xxxxxz')
messages = ['Morning my love', 'I wish you a good night!']
for message in messages:  
        messenger.send_message(message)    

it is able to find_user after which it just does nothing when i break the command it is waiting for something.

    go_to_web = self.wait.until(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\support\wait.py", line 87, in until
    time.sleep(self._poll)

If  you can test yourself see if your basic is working on chrome 103 + latest whatsapp web when performing automated messages.

**Comment by euriconicacio** [comment]
HI, @limlaw. Have you tried the approach I suggested above?

**Comment by limlaw** [comment]
it gives error as below 

Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    wa.just_type_and_send_message("Bla\nBla\nBla")
AttributeError: 'WhatsApp' object has no attribute 'just_type_and_send_message'

**Comment by euriconicacio** [comment]
You need to pull from main, or update your version of the `__init__.py` file with the current version available on this repo.

**Comment by victorterancas** [comment]
It happens the same to me. Whatsapp has changed the "inp_xpath" for just sending a message. Now is a dynamic route:
When the textbox is empty the xpath is:
```
            inp_xpath = (
                '//*[@id="main"]/footer/div[1]/div/span[2]/div/div[2]/div[1]/div/div/p/br'
            )
```

While when I introduce something like "blabla" is:
```
            inp_xpath = (
                '//*[@id="main"]/footer/div[1]/div/span[2]/div/div[2]/div[1]/div/div/p/span'
            )
```
            
I send a gif to show the code:

![(10) WhatsApp - Google Chrome 2022-07-26 18-04-34](https://user-images.githubusercontent.com/92316283/181056324-3e2b53ae-37b2-4f71-8a85-0906903bcdee.gif)

I am trying to solve but i am quite new to xpath and selenium. I find this [webpage](https://www.guru99.com/xpath-selenium.html) that may help.

**Comment by abdullahalshubaili** [comment]
i was not able to send a message also, i have found a solution that worked for me. try changing the inp_xpath to 
'//*[@id="main"]/footer/div[1]/div/span[2]/div/div[2]/div[1]/div/div[1]'

**Comment by euriconicacio** [comment]
Yes, as I said before, we are facing some compatibility issues, and the usage of inp_xpath on send_message and send_message1 are on the roadmap for being updated.

@abdullahalshubaili and @victorterancas: have you tried using the workaround I implemented and suggested above before waving on the issue?

**Comment by victorterancas** [comment]
Sorry @euriconicacio, I am pretty new to github. I will try to find the workaround. 😄.

**Comment by abdullahalshubaili** [comment]
hi @euriconicacio thanks for the help,
 first yes i tried the new version init file in this repo but it didnt work for me and i have tried to insert '\n' in the message and still no luck. however , it was working fine last 2 weeks ago. 
Second, i didnt get what you mean by waving on the issue. im not very familiar with github vocab also

**Comment by Kalebu** [comment]
Hi guys 

I have added a new method ```send_direct_message``` that works well with both saved and unsaved contacts and you can do this by using the below snippet, It does assume your number is saved by default but you can change it by changing the ```saved``` parameter. 

```python
>>> messenger.send_direct_message(mobile, message, saved=True)
```

It does receive the following parameters;

1. **mobile[str]** - The mobile number of the user you want to send the message to
2. **message[str]** - The message you want to send
3. **saved[bool]** - If you want to send to a saved contact or not, default is False

Here is an example on how to use it;

```python
>>> from alright import WhatsApp
>>> messenger = WhatsApp()
>>> >>> messenger.send_direct_message('25573652xxx', 'Hello')
2022-08-14 17:27:57,264 - root -- [INFO] >> Message sent successfuly to 
2022-08-14 17:27:57,264 - root -- [INFO] >> send_message() finished running!
>>> messenger.send_direct_message('25573652xxx', 'Who is This ?', False)
2022-08-14 17:28:30,953 - root -- [INFO] >> Message sent successfuly to 255736524388
2022-08-14 17:28:30,953 - root -- [INFO] >> send_message() finished running!
```
